# Generated by Django 3.2 on 2021-04-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='image',
            field=models.ImageField(default='media/no_img2.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='base',
            name='field',
            field=models.TextField(max_length=50000),
        ),
    ]
