# Generated by Django 3.2 on 2021-04-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0002_auto_20210420_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20)),
                ('field', models.TextField(max_length=50000)),
                ('image', models.ImageField(default='media/no_img2.jpg', upload_to='media')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Base',
        ),
    ]
