# Generated by Django 3.2 on 2021-04-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0004_auto_20210421_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='start_text',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
